apiVersion: v1
kind: Service
metadata:
  name: spark-job-ui
spec:
  type: NodePort  # Use LoadBalancer se estiver em nuvem
  selector:
    app: spark-job
  ports:
    - protocol: TCP
      port: 4040
      targetPort: 4040
      nodePort: 30040  # Porta externa (pode ser qualquer entre 30000-32767)